backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleemfd/blueEconomy
media_folder: static/assets
public_folder: /assets

collections:
  - name: blueEconomy
    label: BlueEconomy
    label_singular: Slider Image
    folder: src/pages/posts/blueEconomy/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BlueEconomy.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Video '
        name: 'video'
        widget: 'file'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }
  - name: beStartup
    label: BE Startup
    label_singular: Slider Image
    folder: src/pages/posts/beStartups/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Startups.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }

  - name: beChallenge
    label: BE Challenge 2021
    label_singular: Be Challenge 2021
    folder: src/pages/posts/bechallenge/
    summary: '{{title1}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Challenge 2021.
    fields:
      - { label: 'Title', name: 'title1', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image1'
        widget: 'image'
        required: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Timeline: key Milestones'
        name: 'timeline'
        widget: 'object'
        fields:
              - {
                  label: 'Preparation',
                  name: preparation,
                  widget: text,
                }
              - {
                  label: 'Round1',
                  name: round1,
                  widget: text,
                }
              - {
                  label: 'Round2',
                  name: round2,
                  widget: text,
                }
              - {
                  label: 'Round3',
                  name: round3,
                  widget: text,
                }
      - label: 'Winner Prizes'
        name: 'prizes'
        widget: 'object'
        fields:
              - {
                  label: 'First Prize',
                  name:   first,
                  widget: string,
                }
              - {
                  label: 'Second Prize',
                  name: second,
                  widget: string,
                }
              - {
                  label: 'Third Prize',
                  name:   third,
                  widget: string,
                }
              - {
                  label: 'Honorable Mention(10 Prizes)',
                  name: honours,
                  widget: string,
                }
      - label: 'Slider 2'
        name: 'slider2'
        widget: 'list'
        fields:
              - {
                  label: 'Title',
                  name:   title,
                  widget: string,
                }
              - {
                  label: 'Description',
                  name: description,
                  widget: text,
                } 
     

  - name: incubation
    label: Incubation Centers
    label_singular: Incubation Centers
    folder: src/pages/posts/betracks/
    summary: '{{firsttitle}}'
    slug: "{{firsttitle}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Tracks.
    fields:
      - { label: 'First Title', name: 'firsttitle', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Second Title', name: 'secondtitle', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true

  - name: funding
    label: Funding Orgnizations
    label_singular: Funding Orgnizations
    folder: src/pages/posts/fundings/
    summary: '{{title}}'
    slug: "{{title}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Funding Orgnizations.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true

  - name: business
    label: Business Competition
    label_singular: Business Competition
    folder: src/pages/posts/business/
    summary: '{{title}}'
    slug: "{{title}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Business Competition.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
  
  - name: international
    label: International Universities
    label_singular: International Universities
    folder: src/pages/posts/international/
    summary: '{{title}}'
    slug: "{{title}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for International Universities.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true

  - name: bestartup
    label: Be Startup
    label_singular: Be Startup
    folder: src/pages/posts/bestartup/
    summary: '{{title}}'
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for International Universities.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - label: 'Small Scale Startups'
        name: 'smallscale'
        widget: 'object'
        fields:
             - { label: 'Title', name: 'title', widget: 'string' }
             - { label: 'Description', name: 'description', widget: 'text' }
             - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Medium Scale Startups'
        name: 'medscale'
        widget: 'object'
        fields:
             - { label: 'Title', name: 'title', widget: 'string' }
             - { label: 'Description', name: 'description', widget: 'text' }
             - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Large Scale Startups'
        name: 'lgscale'
        widget: 'object'
        fields:
            - { label: 'Title', name: 'title', widget: 'string' }
            - { label: 'Description', name: 'description', widget: 'text' }
            - { label: 'Image', name: 'image', widget: 'image' }

  - name: smallscale
    label: Small Scale
    label_singular: Small Scale
    folder: src/pages/posts/smallscale/
    summary: '{{title}}'
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Small Scale.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'City', name: 'city', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }

  
  
  - name: medscale
    label: Medium Scale
    label_singular: Medium Scale
    folder: src/pages/posts/medscale/
    summary: '{{title}}'
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Medium Scale.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'City', name: 'city', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }


  - name: largescale
    label: Large Scale
    label_singular: Large Scale
    folder: src/pages/posts/lgscale/
    summary: '{{title}}'
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Large Scale.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'City', name: 'city', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }

  - name: about
    label: About US
    label_singular: About US
    folder: src/pages/posts/about/
    summary: '{{title1}}-{{title2}}'
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for About US.
    fields:
      - { label: 'First Title', name: 'title1', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description1', widget: 'text', hint: 'Description will be here' }
      - { label: 'First Image', name: 'image1', widget: 'image' }
      - { label: 'First Link', name: 'link1', widget: 'string' }
      - { label: 'Date', name: 'date1', widget: 'date' }
      - { label: 'Second Title', name: 'title2', widget: 'string', tagname: 'h1' }
      - { label: 'Second Description', name: 'description2', widget: 'text', hint: 'Description will be here' }
      - { label: 'Second Image', name: 'image2', widget: 'image' }
      - { label: 'Seccond Link', name: 'link2', widget: 'string' }
      - { label: 'Second Date', name: 'date2', widget: 'date' }

  - name: sponsors_and_partners
    label: Sponsors and Partners
    label_singular: Sponsors and Partners
    folder: src/pages/posts/sponsers_and_partners/
    summary: '{{title1}}-{{title2}}'
    slug: "{{year}}-{{month}}-{{day}}"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for About US.
    fields:
      - { label: 'Partners Title', name: 'title1', widget: 'string', tagname: 'h1' }
      - { label: 'Partners Description', name: 'description1', widget: 'text', hint: 'Description will be here' }
      - { label: 'Partners Link', name: 'link1', widget: 'string' }
      - { label: 'Partners Date', name: 'date1', widget: 'date' }
      - { label: 'Sponsors', name: 'title2', widget: 'string', tagname: 'h1' }
      - { label: 'Sponsors Description', name: 'description2', widget: 'text', hint: 'Description will be here' }
      - { label: 'Sponsors Link', name: 'link2', widget: 'string' }
      - { label: 'Sponsors Creation Date', name: 'date2', widget: 'date' }


  - name: resources
    label: Resources 
    label_singular: Resources
    folder: src/pages/posts/resources/
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Resources.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', tagname: 'h1' }
      - label: 'First Section'
        name: 'first'
        widget: 'object'
        fields:
              - {
                  label: 'Title',
                  name: title,
                  widget: string,
                }
              - {
                  label: 'Decsritpion',
                  name: description,
                  widget: text,
                }
              - {
                  label: 'Link',
                  name: link,
                  widget: string,
                }
      - label: 'Second Section'
        name: 'second'
        widget: 'object'
        fields:
              - {
                  label: 'Title',
                  name: title,
                  widget: string,
                }
              - {
                  label: 'Decsritpion',
                  name: description,
                  widget: text,
                }
              - {
                  label: 'Link',
                  name: link,
                  widget: string,
                }
      - label: 'Third Section'
        name: 'third'
        widget: 'object'
        fields:
              - {
                  label: 'Title',
                  name: title,
                  widget: string,
                }
              - {
                  label: 'Decsritpion',
                  name: description,
                  widget: text,
                }
              - {
                  label: 'Link',
                  name: link,
                  widget: string,
                }
      - label: 'Fourth Section'
        name: 'fourth'
        widget: 'object'
        fields:
              - {
                  label: 'Title',
                  name: title,
                  widget: string,
                }
              - {
                  label: 'Decsritpion',
                  name: description,
                  widget: text,
                }
              - {
                  label: 'Link',
                  name: link,
                  widget: string,
                }


  - name: contact_us
    label: Contact US
    label_singular: Contact
    folder: src/pages/posts/contact_us/
    summary: '{{address}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Contact US.
    fields:
      - { label: 'Address', name: 'address', widget: 'text' }
      - { label: 'Phone Number', name: 'phone_number', widget: 'text' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'MAP', name: 'map', widget: 'map' }


  - name: video_section
    label: Blue Economy Video Section
    label_singular: Contact
    folder: src/pages/posts/blueeconomy/video_sction/
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Contact US.
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Descripion', name: 'description', widget: 'text' }
      - { label: 'Video', name: 'video', widget: 'file' }
      

  - name: list_section
    label: Blue Economy List Section
    label_singular: Blue Economy List Section
    folder: src/pages/posts/blueeconomy/list_section/
    summary: '{{title}}'
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Contact US.
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Image', name: 'image', widget: 'image' }



  
     
