backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleemfd/blueEconomy
media_folder: static/assets
public_folder: /assets

collections:
  - name: blueEconomy
    label: BlueEconomy
    label_singular: Slider Image
    folder: src/pages/posts/blueEconomy/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BlueEconomy.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Video '
        name: 'video'
        widget: 'file'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }
  - name: beStartup
    label: BE Startup
    label_singular: Slider Image
    folder: src/pages/posts/beStartups/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Startups.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }

  - name: beChallenge
    label: BE Challenge 2021
    label_singular: Be Challenge 2021
    folder: src/pages/posts/bechallenge/
    summary: '{{title1}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Challenge 2021.
    fields:
      - { label: 'Title', name: 'title1', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image1'
        widget: 'image'
        required: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Timeline: key Milestones'
        name: 'timeline'
        widget: 'object'
        fields:
              - {
                  label: 'Preparation',
                  name: preparation,
                  widget: text,
                }
              - {
                  label: 'Round1',
                  name: round1,
                  widget: text,
                }
              - {
                  label: 'Round2',
                  name: round2,
                  widget: text,
                }
              - {
                  label: 'Round3',
                  name: round3,
                  widget: text,
                }
      - label: 'Winner Prizes'
        name: 'prizes'
        widget: 'object'
        fields:
              - {
                  label: 'First Prize',
                  name:   first,
                  widget: string,
                }
              - {
                  label: 'Second Prize',
                  name: second,
                  widget: string,
                }
              - {
                  label: 'Third Prize',
                  name:   third,
                  widget: string,
                }
              - {
                  label: 'Honorable Mention(10 Prizes)',
                  name: honours,
                  widget: string,
                }
      - label: 'Slider 2'
        name: 'slider2'
        widget: 'list'
        fields:
              - {
                  label: 'Title',
                  name:   title,
                  widget: string,
                }
              - {
                  label: 'Description',
                  name: description,
                  widget: text,
                } 
     

  - name: betracks
    label: Be Tracks
    label_singular: Be Tracks
    folder: src/pages/posts/betracks/
    summary: '{{firsttitle}}'
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Tracks.
    fields:
      - { label: 'First Title', name: 'firsttitle', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Second Title', name: 'secondtitle', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true

  - name: funding
    label: Funding Orgnizations
    label_singular: Funding Orgnizations
    folder: src/pages/posts/fundings/
    summary: '{{title}}'
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Funding Orgnizations.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true

  - name: business
    label: Business Competition
    label_singular: Business Competition
    folder: src/pages/posts/business/
    summary: '{{title}}'
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Business Competition.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
  
  - name: international
    label: International Universities
    label_singular: International Universities
    folder: src/pages/posts/international/
    summary: '{{title}}'
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for International Universities.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'Project Link', name: 'projectLink', widget: 'string' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
     
